/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_looa_ndkencode_SNNative */

#ifndef _Included_org_looa_ndkencode_SNNative
#define _Included_org_looa_ndkencode_SNNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_looa_ndkencode_SNNative
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_looa_ndkencode_SNNative_stringFromJNI
        (JNIEnv *, jclass);

/*
 * Class:     org_looa_ndkencode_SNNative
 * Method:    encode
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_looa_ndkencode_SNNative_encode
        (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
